version: "3.7"
services:
  db:
    container_name: db
    restart: always
    image: postgres
    network_mode: bridge
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
  flask:
    container_name: flask
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  database_data:
    driver: local